version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: nuxeodb
      POSTGRES_DB: nuxeodb
      POSTGRES_PASSWORD: nuxeodb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
